### ISSUE TITLE
Mounting directory on external sd

### ISSUE THREAD

**Issue by grepper** [codebucketdev/magisk-foldermount#5]
The regex validating the Sd card doesn't work on my phone running RR (based on lineage for athene), as the uuid uses lower case letters. 

Changing '[0-9AF]{4}-[0-9A-F]{4}' to '[0-9a-fA-F]{4}-[0-9a-fA-F]{4}' worked for me.

**Comment by codebucketdev** [comment]
Thanks for your finding, I've fixed that with 4cdebc6 so it will be included in the next release!
