### ISSUE TITLE
What's the Licence?

### ISSUE THREAD

**Issue by xbach** [codebucketdev/magisk-foldermount#6]
Hi! 

First of all, thanks for all of your work!

I am just wondering what is the licence for this code? I made some changes, including implementing some basic form of listFunc and rebindFunc. Just wondering about the licence before I push the changes to my fork :)

Thanks!

**Comment by codebucketdev** [comment]
Thanks and sorry for the late response, I actually forgot to add the license file for GPL v3 :smile:

As you can see I've added the license file with f6f3c09, so you should be able to create your pull request without any fear! Hope to see your contribution soon, as I'm currently having time again for this project.
